jlu5/ansible-dn42

roles/config-bird2/config/peers/nl-ams02/spf.conf, roles/config-wireguard/config/nl-ams02.yml
=> Update settings for new NL node

roles/config-wireguard/config/sgp.yml
I recently found that your HK node has been replaced by an SG node, please also switch to my SG node. Thanks
=> TMs - Change Node to SG

roles/config-bird2/config/peers/sea/routedbits.conf, roles/config-wireguard/config/sea.yml
Hello again!
We recently got our Seattle PoP up and would love to peer with you in Seattle as well!
=> Peer with RoutedBits AS4242420207 in Seattle, WA

roles/config-bird2/config/peers/ams/routedbits.conf, roles/config-wireguard/config/ams.yml
=> Add RoutedBits (AS4242420207) peering in AMS

roles/config-bird2/config/peers/sjc/dnsense.conf, roles/config-wireguard/config/sjc.yml
=> sjc: add AS4242423117 / dnsense peering

roles/config-bird2/config/peers/ams/dingemans.conf, roles/config-wireguard/config/ams.yml
Changed domain, collapsed v4&v6 sessions into extended next hop
=> Update peering for: AS210074 / dingemans, ams

roles/config-bird2/config/peers/tyo/cmcc.conf, roles/config-wireguard/config/tyo.yml
I would like to keep my endpoint info private, so I leave it empty as it's said on your peering page.
=> Add AS4242421686 peering in TYO

roles/config-bird2/config/peers/hkg/yuchow.conf, roles/config-wireguard/config/hkg.yml
Add AS4242421260,connect to HKG node
=> Add AS4242421260,connect to HKG node

roles/config-bird2/config/peers/hkg/sidereal.conf, roles/config-bird2/config/peers/lax/sidereal.conf, roles/config-bird2/config/peers/lon/sidereal.conf, roles/config-wireguard/config/hkg.yml, roles/config-wireguard/config/lax.yml, roles/config-wireguard/config/lon.yml, roles/config-wireguard/config/ymq.yml
New peerings over in Europe / Asia, and updating an existing record for my Toronto node. Thanks!
=> add europe/asia AS4242422016 peerings, update DNS

roles/config-bird2/config/peers/fra/m4rc3l.conf, roles/config-wireguard/config/fra.yml
I've just turned my infra back on yesterday. ;)
=> readd m4rc3l-as

roles/config-bird2/config/peers/lon/baragoon.conf, roles/config-wireguard/config/lon.yml
=> AS4242421732

roles/config-wireguard/config/sjc.yml, roles/config-wireguard/config/yvr.yml
=> CDUBS Changes

roles/config-wireguard/config/tyo.yml
I lost my keypair due to a disk failure.
=> Change cowgl public key & wg port

roles/config-wireguard/config/ams.yml, roles/config-wireguard/config/chi.yml, roles/config-wireguard/config/tyo.yml
=> Add links to dn42-sdubs

roles/config-wireguard/config/hkg.yml
=> hkg: modify peering for CdubS/AS4242420566

roles/config-wireguard/config/lon.yml
=> Add peering for AS4242420202 to LON

roles/config-wireguard/config/ymq.yml
=> Add peering for AS4242420202 to YMQ

roles/config-wireguard/config/hkg.yml, roles/config-wireguard/config/sjc.yml
Wrong IP in initial submission
=> Fix AS4242420202 config for SJC

roles/config-wireguard/config/tyo.yml
=> tyo: add cowgl / AS4242423999

roles/config-wireguard/config/lon.yml
This PR adds peering to my UKSE1 node over link local addresses with MP BGP and extended next hop.
Thanks for considering peering :)
(Force push was to ensure commit was signed and not showing as unverified)
=> lon: add AS-SM1755-DN42 / AS4242421755

roles/config-wireguard/config/hkg.yml, roles/config-wireguard/config/sjc.yml
=> Add AS4242423377 peering at HKG SJC

roles/config-wireguard/config/ams.yml
=> Leave dn42

roles/config-wireguard/config/sjc.yml
Adding my California node for sjc peering test.
=> sjc:add PrefixLabs US-03 / 4242421240

roles/config-wireguard/config/sjc.yml
=> sjc: add cowgl / AS4242423999

roles/config-wireguard/config/sto.yml
=> sto: add myxoz / AS4242420166

roles/config-wireguard/config/ams.yml
=> ams: add cowgl / AS4242423999

roles/config-wireguard/config/hkg.yml, roles/config-wireguard/config/sjc.yml
update wireguard pubkey@sjc
added new peer to hkg
=> sjc,hkg: update/add Ferrets_Network / 4242423077

roles/config-wireguard/config/syd.yml
Adding my new Sydney node to our peerings per TG chat. 
Thanks!
=> syd:add PrefixLabs AU-01 / 4242421240

roles/config-wireguard/config/ams.yml, roles/config-wireguard/config/lon.yml, roles/config-wireguard/config/sto.yml
Added a second node for redundancy (STO).
Changed AMS to peer with my DE node instead of UK node.
=> sto: added AleMal-Network / 4242421525 ams: changed node AleMal-Network / 4242421525

roles/config-wireguard/config/mum.yml
Per IRC chat, Mumbai <-> Bangalore peering. 
Thanks for peering once again, takes us to 6 :-).
=> mum:add PrefixLabs IN-01 / 4242421240

roles/config-wireguard/config/syd.yml
=> syd: add BadAimWeeb / AS4242423797

roles/config-wireguard/config/chi.yml
=> chi: add be0ba / AS4242420224

roles/config-wireguard/config/mum.yml
=> mum: add CdubS / AS4242420566

roles/config-wireguard/config/ams.yml
=> ams: add BadAimWeeb / AS4242423797

roles/config-wireguard/config/hkg.yml, roles/config-wireguard/config/sjc.yml
I added a new node in SJC and changed HongKong node wireguard pubkey. Thank you.
=> sjc,hkg: add and update wireguard pubkey for CMCC / AS4242421686

roles/config-wireguard/config/ams.yml, roles/config-wireguard/config/chi.yml, roles/config-wireguard/config/hkg.yml, roles/config-wireguard/config/sgp.yml, roles/config-wireguard/config/syd.yml
=> ams,chi,hkg,sgp,syd: add chi,hkg,sgp; modify ams,syd / AS4242423797

roles/config-wireguard/config/tyo.yml, roles/config-wireguard/config/ymq.yml
Hello jlu5!
Adding two peerings in this PR.
=> ymq,tyo: add MAIYUN-DN42 / AS4242420893

roles/config-wireguard/config/ams.yml
Hi!
Thanks for updating your config,
Best,
Hyacinthe
=> ams: update remote for flipflap / AS4242420263
